library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity neuron_dp_subtractive_sdsp is
    generic (
        neuron_bit_width      : positive := 16;
        inh_weights_bit_width : positive := 3;
        exc_weights_bit_width : positive := 3;
        shift                 : natural  := 4
    );
    port (
        v_th          : in  signed(neuron_bit_width-1 downto 0);
        inh_weight    : in  signed(inh_weights_bit_width-1 downto 0);
        exc_weight    : in  unsigned(exc_weights_bit_width-1 downto 0);
        clk           : in  std_logic;
        update_sel    : in  std_logic_vector(1 downto 0);
        add_or_sub    : in  std_logic;
        v_en          : in  std_logic;
        v_rst_n       : in  std_logic;
        teacher_apply : in std_logic := '0';
        teacher_current : in signed(neuron_bit_width-1 downto 0) := (others => '0');
        exceed_v_th   : out std_logic;
        v_mem         : out signed(neuron_bit_width-1 downto 0)
    );
end entity neuron_dp_subtractive_sdsp;

architecture structural of neuron_dp_subtractive_sdsp is
    signal update       : signed(neuron_bit_width-1 downto 0);
    signal v_value      : signed(neuron_bit_width-1 downto 0);
    signal v            : signed(neuron_bit_width-1 downto 0);
    signal v_shifted    : signed(neuron_bit_width-1 downto 0);
    signal exc_extended : signed(neuron_bit_width-1 downto 0);
    signal inh_extended : signed(neuron_bit_width-1 downto 0);
    signal selected_update : signed(neuron_bit_width-1 downto 0);
    signal selected_subtract, selected_v_en : std_logic;
begin
    -- SDSP weights are unsigned register codes. Inhibitory weights retain the
    -- signed representation generated by Spiker.
    exc_extended <= signed(resize(exc_weight, neuron_bit_width));
    inh_extended <= resize(inh_weight, neuron_bit_width);
    v_mem        <= v;

    v_shifter : entity work.shifter
        generic map (N => neuron_bit_width, shift => shift)
        port map (shifter_in => v, shifted_out => v_shifted);

    update_mux : entity work.mux_4to1_signed
        generic map (bitwidth => neuron_bit_width)
        port map (
            mux_sel => update_sel,
            in0 => v_th,
            in1 => v_shifted,
            in2 => exc_extended,
            in3 => inh_extended,
            mux_out => update
        );

    -- Reuse the saturating membrane adder to add teacher current once per
    -- step. With teacher_apply low, the generated neuron path is unchanged.
    selected_update <= teacher_current when teacher_apply = '1' else update;
    selected_subtract <= '0' when teacher_apply = '1' else add_or_sub;
    selected_v_en <= v_en or teacher_apply;

    update_add_sub : entity work.add_sub
        generic map (N => neuron_bit_width)
        port map (
            in0 => v,
            in1 => selected_update,
            add_or_sub => selected_subtract,
            add_sub_out => v_value
        );

    v_reg : entity work.reg_signed_sync_rst
        generic map (N => neuron_bit_width)
        port map (
            clk => clk,
            en => selected_v_en,
            rst_n => v_rst_n,
            reg_in => v_value,
            reg_out => v
        );

    fire_cmp : entity work.cmp_gt
        generic map (N => neuron_bit_width)
        port map (in0 => v, in1 => v_th, cmp_out => exceed_v_th);
end architecture structural;
